### ISSUE TITLE
Server response decode error?

### ISSUE THREAD

**Issue by duongxinh2003** [iohao/ioGameSimpleOne#3]
When I get response by command 1-1 from server, the expected result like:
``jackson, hello, jackson !``
But when I decoded from byte array from response server:
``
[8, 1, 16, 0, 24, 129, 128, 4, 32, 0, 50, 27, 10, 25, 106, 97, 99, 107, 115, 111, 110, 44, 32, 104, 101, 108, 108, 111, 44, 32, 106, 97, 99, 107, 115, 111, 110, 32, 33, 56, 3]
``
It cannot decode look like response, actual seem add some symbols:
```
�� 2
jackson, hello, jackson !8
```
Here is some script to decode this:
```
const arr = new Uint8Array([8, 1, 16, 0, 24, 129, 128, 4, 32, 0, 50, 27, 10, 25, 106, 97, 99, 107, 115, 111, 110, 44, 32, 104, 101, 108, 108, 111, 44, 32, 106, 97, 99, 107, 115, 111, 110, 32, 33, 56, 3]);
const decoder = new TextDecoder('utf8');
const str = decoder.decode(arr);
console.log(str)
```

**Comment by iohao** [comment]
Simulate client request data
https://github.com/iohao/ioGameSimpleOne/blob/e898ecbbbe1db02b7e7aa368871bee0801c562b4/src/main/java/com/iohao/one/example/client/DemoClient.java#L31-L46

or see https://github.com/iohao/ioGame/issues/312

**Comment by duongxinh2003** [comment]
I just downloaded the demo of JS client at https://github.com/iohao/ioGameExamples/tree/main/SimpleExample/example/example-codec-json/src/main/resources/WEB-INF/static and ran it. It seems not working.
<img width="763" alt="image" src="https://github.com/user-attachments/assets/352eb231-5895-4338-a78b-9da51769476f">
Edit: Sorry for my fault, I don't change the server demo by JsonDataCodec()
